config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  root 'static_pages#home'
    #get '/articles', to: 'articles#index'
    #get '/articles/new', to: 'articles#new', as: :new_article
    #get '/articles/:id', to: 'articles#show', as: :article
    #post '/articles', to: 'articles#create'
    #get '/articles/:id/edit', to: 'articles#edit', as: :edit_article
    #patch '/articles/:id', to: 'articles#update'
    #delete '/articles/:id', to: 'articles#destroy'
    # The 7 lines above can be replaced with resources :articles
  devise_scope :user do
    post '/users/sign_up', to: 'devise/registrations#create', as: :new_user_reg
  end
  devise_for :users
  
  resources :moonies  
  resources :users 
  resources :articles, only: [:create, :destroy, :index]
  post '/articles', to: 'articles#create', as: :article_create

  resources :comments 
  post '/comments', to: 'comments#create', as: :comment_create

  get '/help', to: 'static_pages#help'
  get '/about', to: 'static_pages#about'
  get '/goodbye', to: 'static_pages#goodbye'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/article.rb
class Article < ApplicationRecord
  belongs_to :user
  has_many :comments
  default_scope -> { order(created_at: :desc) }
  validates :title, presence: true, length: {minimum: 5, maximum: 90}
  validates :body, presence: true, length: {minimum: 5}
  # dependent: :destroy is used to avoid the foreign key constraint error
  # This allows for all comments tied to an article to be destroyed as the article is deleted
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :article
  belongs_to :user
end

app/models/user.rb
class User < ApplicationRecord
  has_many :articles
  has_many :comments
  has_one_attached :avatar
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
        :recoverable, :rememberable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :configure_permitted_parameters, if: :devise_controller?

  protected 
    def configure_permitted_parameters 
      devise_parameter_sanitizer.permit(:sign_up, keys: [:name])
      devise_parameter_sanitizer.permit(:account_update) { 
        |u| u.permit(:avatar, :name, :email, :password, :password_confirmation, :current_password) 
      } 
    end

  private
    def after_sign_out_path_for(resource_or_scope)
      goodbye_path
    end

    def after_sign_in_path_for(resource_or_scope)
      moony_path(current_user)
    end
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
  before_action :authenticate_user!, only: [:create, :destroy]

  def index 
    @articles = Article.all.page(params[:page]).per(10)
  end

  def create 
    @article = current_user.articles.build(article_params)
    if @article.save
      redirect_to moony_path(@article.user)
    else 
      flash[:article_errors] = @article.errors.full_messages
      redirect_to moony_path(@article.user)
    end
  end

  def destroy 
    @article = Article.find(params[:id])
    @article.destroy
    flash[:success] = "Moony article deleted"
    if request.referrer.nil? || request.referrer == articles_url
      redirect_to articles_path
    else
      redirect_to request.referrer
    end
  end

  private
    def article_params
      params.require(:article).permit(:title, :body)
    end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  # allow only authenticated user to destroy comments on article
  #http_basic_authenticate_with name: "dhh", password: "secret", only: :destroy

  def create
    @article = Article.find(params[:article_id])
    @comment = @article.comments.create(comment_params)
    redirect_to root_url
  end

  def destroy
    @article = Article.find(params[:article_id])
    @comment = @article.comments.find(params[:id])
    @comment.destroy
    redirect_to root_url
  end
  
  private
    def comment_params
      params.require(:comment).permit(:user_id, :article_id, :body)
    end
end

app/controllers/moonies_controller.rb
class MooniesController < ApplicationController
  def show
    @user = User.find(params[:id])
    @articles = @user.articles.page(params[:page]).per(10)

    @article = current_user.articles.build if user_signed_in?
    p @article
  end     

  def edit 
    @user = User.find(params[:id])
  end
end

app/controllers/registrations_controller.rb
class RegistrationsController < Devise::RegistrationsController

  private
    def sign_up_params 
      params.require(:user).permit(:name, :email, :password, :password_confirmation)
    end
    def account_update_params
      params.require(:user).permit(:name, :email, :password, :password_confirmation, :current_password)
    end
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def home
  end
  
  def help
  end

  def about
  end

  def goodbye
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/views/articles/_article.html.erb
<li id="article-<%= article.id %>">
  <div class="row">
    <span class="col-xs-6 col-sm-4 article-avatar">
      <% if article.user.avatar.attached? %>
        <%= image_tag article.user.avatar , class: "img-rounded article-avatar" %>
      <% else %>
        <%= image_tag("pixel_star_purple.png", alt: "Default Avatar", class: "img-rounded article-avatar") %>
      <% end %>
    </span>
    <span class="article-user">
      <%= link_to article.user.name , moony_path(article.user) %>
    </span><br>
    <span class="article-title">
      <%= article.title %>
    </span>
  </div>

  <div class="row">
    <span class="article-content">
      <%= article.body %>
    </span><br>

    <span class="article-timestamp">
      Published <%= time_ago_in_words(article.created_at) %> ago.
    </span>

    <span class="article-links">
      <% if article.user == current_user %>
        <%= link_to "Delete", article, method: :delete, data: {confirm: "You sure you want to delete this Moony article?"} %>
      <% end %>
    </span><br>
  </div>

  <div class="container-fluid comment-box">
    <%= render "comments/comment_form" %>
  </div>
</li>

app/views/articles/_article_form.html.erb
<div class="">
  <% if !!flash[:article_errors] %>
    <% flash.each do |type, messages| %>
      <div class="alert alert-info">
        <% messages.each do |msg| %>
            <li><%= msg %></li>
        <% end %>
      </div>
    <% end %>
  <% end %>

  <%= form_with(model: @article , local: true, html: { class: "center form-horizontal" } ) do |f| %>
    <div class="form-group" >
      <%= f.text_field :title, placeholder: " Title...", size: "35", class: "title-field" %>
    </div>

    <div class="form-group">
      <%= f.text_area :body, placeholder: " Compose new article...", size: "40x10", class: "body-field" %>
    </div>

    <%= f.submit "Post Moony Article", class: "btn btn-primary post-btn" %>
  <% end %>
</div>

app/views/articles/index.html.erb
<%= render "shared/flash_display" %>

<div class="greeting animate-fade">
  Moon Feed
</div>

<div class="paginate-bar animate-fade">
  <%= paginate @articles %>
</div>
<ul class="articles">
  <%= render @articles %>
</ul>
<div class="paginate-bar animate-fade">
 <%= paginate @articles %>
</div>

app/views/comments/_comment.html.erb
<li id="comment-<%= comment.id %>">
  <div class="row">
    <span class="col-xs-6 col-sm-4 comment-avatar">
      <% if comment.user.avatar.attached? %>
        <%= image_tag comment.user.avatar , class: "img-rounded comment-avatar" %>
      <% else %>
        <%= image_tag("pixel_star_purple.png", alt: "Default Avatar", class: "img-rounded comment-avatar") %>
      <% end %>
    </span>

    <span class="comment-user">
      <%= link_to comment.user.name , moony_path(comment.user) %>
    </span><br>
    
    <div class="row">
      <span class="comment-content">
        <%= comment.body %>
      </span><br>

      <span class="comment-timestamp">
        Commented <%= time_ago_in_words(comment.created_at) %> ago.
      </span>

      <span class="comment-links"> 
        <% if comment.user == current_user %>
          <%= link_to "Delete comment", comment, method: :delete, data: {confirm: "You sure you want to delete this comment?"} %>
        <% end %>
      </span>
    </div>
  </div>
</li>

app/views/comments/_comment_form.html.erb

<div class="col-xs-4 col-md-1">
  <% if current_user.avatar.attached? %>
    <%= image_tag current_user.avatar, class: "img-rounded comment-avatar"%>
  <% else %>
    <%= image_tag("pixel_star_purple.png", alt: "Default Avatar", class: "img-rounded comment-avatar") %>
  <% end %>
</div>

<div class="col-xs-14 col-md-11">
  <%= form_with(model: @comment, local: true, url: comment_create_path) do |f| %>
    <%= f.text_area :body, placeholder: " Compose new comment...", size: "70", class: "body-field comment-body" %> 

    <%= f.submit "Post Moony Comment", class: "btn btn-primary post-btn comment-button" %>
  <% end %>
</div>

app/views/layouts/_header.html.erb
<header class="navbar navbar-fixed-top">
  <div class="container-fluid">
    <%= link_to "Moon Moon", root_path, id: "logo" %>
    <%= link_to image_tag("moon_logo.png", alt: "Moon Blog Logo", width: "50", id: "logo_pic"), root_path %>
    <nav>
      <ul class="nav navbar-nav navbar-right">

        <% if !user_signed_in?%>
          <li><%= link_to "Home", root_path %></li>
        <% else %>
          <li><%= link_to "Dashboard", articles_path %></li>
        <% end %>

        <li><%= link_to "About", about_path %></li>
        <li><%= link_to "Help", help_path %></li>

        <% if user_signed_in?%>
          <li class="dropdown">
            <a href="#" class="dropdown-toggle" data-toggle="dropdown">
              My Account<b class="caret"></b>
            </a>
            <ul class="dropdown-menu">
              <li><%= link_to "Profile", moony_path(current_user) %>
              <li><%= link_to "Settings", edit_user_registration_path	 %>
              <li><%= link_to "Log out", destroy_user_session_path, method: :delete, data: {confirm: "Fellow moonie, are you sure you want to log out?"}%></li>
              <li class="divider"></li>
              <li><%= link_to "Contact Sailor Senshii", '#' %></li>
            </ul>
          </li>
        <% else %>
          <li><%= link_to "Log in", new_user_session_path %></li>
        <% end %>
      </ul>
    </nav>
  </div>
</header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Moon Blog</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>

  </head>

  <body>
    <%= render 'layouts/header' %>
      <%= yield %>
  </body>
</html>

app/views/moonies/_moony_info.html.erb
<div class="profile-snippet center-block">
  <% if @user.avatar.attached? %>
    <%= image_tag @user.avatar , class: "img-responsive img-circle center-block profile-avatar" %>
  <% else %>
    <%= image_tag("pixel_star_purple.png", alt: "Default Avatar", class: "img-responsive img-circle center-block profile-avatar") %>
  <% end %>

  <div class="center profile-info">
    Moony since <%= @user.created_at.strftime("%b %d, %Y") %>
  </div>
</div>

app/views/moonies/edit.html.erb
<h1>Settings</h1>

<%= form_for @user do |f| %>
  <%= f.label :avatar %>
  <%= f.file_field :avatar %>
<% end %>

app/views/moonies/show.html.erb
<%= render "shared/flash_display" %>

<div class = "greeting animate-fade">
  <% if @user == current_user %>
    Hello again, <%= @user.name %>
  <% else %>
    <%= @user.name %>'s Moonie Profile
  <% end %>
</div>

<div class="row">
  <div class="col-xs-6 col-sm-4 animate-fade">
    <%= render "moonies/moony_info" %>
    <% if @user == current_user %>
      <%= render "articles/article_form" %>
    <% end %>
  </div>

  <div class="col-xs-12 col-sm-6 col-md-8">
    <div class="subtitle animate-fade">
      Personal Moon Feed
    </div>

    <% if @user.articles.any? %>
      <div class="paginate-bar animate-fade">
        <%= paginate @articles %>
      </div>
      <ul class="articles">
        <%= render @articles %>
      </ul>
      <div class="paginate-bar animate-fade">
        <%= paginate @articles %>
      </div>     
    <% else %>
      <div class="moony-note animate-fade">
      <% if @user == current_user %>
        You have no articles yet.
      <% else %>
        This moony has no articles yet. 
      <% end %>
    <% end %>
  </div>
</div>

app/views/shared/_error_messages.html.erb
<% if object.errors.any? %>
  <div id="error_explanation">
    <div class="alert alert-danger">
      The form contains <%= pluralize(object.errors.count, "error") %>.
    </div>
    <ul>
      <% object.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/shared/_flash_display.html.erb
<div class="container center">
  <% if !!flash[:success] %>
    <div class="alert alert-success">
      <%= flash[:success]%>
    </div>
  <% end %>
</div>

app/views/static_pages/about.html.erb
<div class="center animate-fade">
  <h1>About</h1>
</div>

app/views/static_pages/goodbye.html.erb
<div class="container animate-fade">
  <h1>Oh dear moonie,</h1>
  <h1>Don't say goodbye, </h1>
  <h1>Only say goodnight. </h1>
</div>

app/views/static_pages/help.html.erb
<div class = "center animate-fade">
  <h1>Help</h1>
</div>

app/views/static_pages/home.html.erb
<div class= "center container jumbotron animate-fade">
  <h1>The Moon Blog</h1>
  <h2>A blog by the moonies for all the world's other moonies</h2>
  <% if !user_signed_in? %>
    <%= button_to "Become a Moonie", new_user_reg_path , class: "btn btn-primary", id: "sign_up_btn" %>
  <% end %>
</div>

<div class = "container">

</div>